version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/usr/app/src
      - ./.env:/usr/app/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    volumes:
      - ./mongodb:/var/lib/mongodb/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASS}@${MONGO_DATABASE}:${MONGO_DB_PORT}/
    links:
      - mongo
