version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/usr/app/src
      - ./.env:/usr/app/.env
