FROM node:16-alpine3.13
ENV NODE_VERSION 16.13.0

COPY package.json package-lock.json src/infra/database/orm/prisma/schema.prisma ./
RUN npm ci

FROM node:16-alpine3.13
ENV NODE_VERSION 16.13.0
WORKDIR /usr/app
COPY --from=0 node_modules/ node_modules/
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
